global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'supabase-edge-functions'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:54321']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'supabase_edge_function_.*'
        action: keep

  - job_name: 'auth-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:54321']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'auth_.*'
        action: keep

  - job_name: 'kyc-processing'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:54321']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'kyc_.*'
        action: keep

rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093'] 